"""first commit

Revision ID: c930c3cea8a7
Revises:
Create Date: 2024-06-27 14:56:18.002694

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "c930c3cea8a7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
