"""create user and blog table migrations

Revision ID: f6617cfa5782
Revises: c930c3cea8a7
Create Date: 2024-06-27 15:42:03.945124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6617cfa5782'
down_revision = 'c930c3cea8a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
